import useTranslation from 'next-translate/useTranslation';
import Container from '@components/Container';
import { ThemeContextProvider } from '@context/ThemeContext';

import 'normalize.css/normalize.css';
import './layout.scss';

export const metadata = {
  // TODO: da error al extraer la cobertura (lo dejo comentado de momento)
  title: 'Create Next App - Rafa',
  description: 'Generated by create next app',
  viewport: 'width=device-width,height=device-height,initial-scale=1,maximum-scale=1,user-scalable=no,minimal-ui,viewport-fit=cover',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { lang } = useTranslation('home');

  return (
    <html lang={lang}>
      <body>
        <ThemeContextProvider>
          <Container>
            <div className="content">
              <main>{children}</main>
            </div>
          </Container>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
