import 'normalize.css/normalize.css';
import './layout.scss';
import useTranslation from 'next-translate/useTranslation';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { lang } = useTranslation('home');

  return (
    <html lang={lang}>
      <body>{children}</body>
    </html>
  );
}
